services:
  backend:
    build:
      context: ./main_app/backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./main_app/backend:/app
      - ./main_app/images:/app/images
  frontend:
    build:
      context: ./main_app/frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./main_app/frontend:/app 