AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024

Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .                      # package everything here
      Runtime: python3.12             # updated to match closer to your version
      Handler: app.lambda_handler     # our new handler
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: ./inv-processing-authentication-f9e50adadbc5.json
      Events:
        ReceiveApi:
          Type: Api
          Properties:
            Path: /receive
            Method: post
