AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
  Api:
    BinaryMediaTypes:
      - "image/*"
      - "application/octet-stream"
      - "multipart/form-data"

Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .                      # package everything here
      Runtime: python3.12             # updated to match closer to your version
      Handler: app.lambda_handler     # our new handler
      Environment:
        Variables:
          GOOGLE_APPLICATION_CREDENTIALS: ./inv-processing-authentication-f9e50adadbc5.json
          WS_ENDPOINT: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: WSConnections
        - DynamoDBCrudPolicy:
            TableName: InvoiceMetrics
        - Statement:
            Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*"
      Events:
        ReceiveApi:
          Type: Api
          Properties:
            Path: /receive
            Method: post

  # WebSocket API (referenced in environment variables)
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: InvoiceDashboardWS
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  # DynamoDB Tables
  WSConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WSConnections
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  InvoiceMetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: InvoiceMetrics
      AttributeDefinitions:
        - AttributeName: invoiceId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: invoiceId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # WebSocket Routes
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Sub integrations/${ConnectInteg}

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Sub integrations/${DisconnectInteg}

  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadFunction.Arn}/invocations

  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadFunction.Arn}/invocations

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
    Properties:
      ApiId: !Ref WebSocketApi

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: dev
      Description: Dev Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref WebSocketApi

  # Permissions for WebSocket API to invoke Lambda
  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UploadFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*

Outputs:
  WebSocketEndpoint:
    Description: WebSocket API endpoint for dashboard
    Value: !Sub wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev
    Export:
      Name: !Sub ${AWS::StackName}-websocket-endpoint
